version: "3"
services:
  proxy:
    build: .
    env_file: .env
    ports:
      - 80:80

  frontend_alunos:
    build: ./FrontEnd/
    env_file: ./FrontEnd/.env

  db:
    image: postgres:11.2-alpine
    restart: always
    env_file: ./Backend/.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  backend:
    build: ./Backend
    env_file: ./Backend/.env
    depends_on:
      - db
      - redis
    volumes:
      - ./Backend/media:/code/sme_alunos_apps/media
      - ./Backend/staticfiles:/code/staticfiles

  redis:
    image: redis:5.0.0-alpine

networks:
  default:
    external:
      name: coad-network
